mapping = {
    'e': 'stick l y 100',
    's': 'stick l x -100',
    'd': 'stick l y -100',
    'f': 'stick l x 100',
    'i': 'X',
    'j': 'Y',
    'k': 'B',
    'l': 'A',
    'E': 'DPAD_UP',
    'S': 'DPAD_LEFT',
    'D': 'DPAD_DOWN',
    'F': 'DPAD_RIGHT',
    'Key.up': 'stick r y 100',
    'key.left': 'stick r x -100',
    'key.down': 'stick r y -100',
    'key.right': 'stick r x 100',
    'key.enter': 'PLUS',
    'key.backspace': 'MINUS',
    'w': 'ZL',
    'r': 'L',
    'u': 'R',
    'o': 'ZR',
    'g': 'L_STICK_PRESS',
    'h': 'R_STICK_PRESS',
    't': 'CAPTURE',
    'y': 'HOME',
}
